# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4cf87a55-59d8-4188-81f7-6fb1728539e5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."bowsprit".device = "/dev/disk/by-uuid/d24958c7-5b1d-4064-89dc-dff99da331c3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4FC5-B4CD";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/86a6c8e8-cda9-45a6-828f-561dd21ef5d2"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
